name: test_case
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  retrofit: ">=3.0.0 <4.0.0"
  injectable: ^2.1.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  dio: ^4.0.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ">=4.0.0 <5.0.0"
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
